-- Create tables for "test_db"
GRANT ALL PRIVILEGES ON DATABASE test_db TO test_user;

\c test_db;

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "TestLevels" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(1000) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TestLevels" PRIMARY KEY ("Id")
);

CREATE TABLE "TestRuns" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ExecutedAt" timestamp with time zone NOT NULL,
    "Environment" character varying(200) NOT NULL,
    "Notes" character varying(4000) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TestRuns" PRIMARY KEY ("Id")
);

CREATE TABLE "TestCases" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(100) NOT NULL,
    "Description" character varying(2000) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "TestLevelId" integer NOT NULL,
    CONSTRAINT "PK_TestCases" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TestCases_TestLevels_TestLevelId" FOREIGN KEY ("TestLevelId") REFERENCES "TestLevels" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "TestResults" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ActualResult" text NOT NULL,
    "TestCaseId" integer NOT NULL,
    "TestRunId" integer NOT NULL,
    "Status" integer NOT NULL,
    "ExecutedAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TestResults" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TestResults_TestCases_TestCaseId" FOREIGN KEY ("TestCaseId") REFERENCES "TestCases" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TestResults_TestRuns_TestRunId" FOREIGN KEY ("TestRunId") REFERENCES "TestRuns" ("Id") ON DELETE RESTRICT
);

INSERT INTO "TestLevels" ("Id", "CreatedAt", "Description", "Name", "UpdatedAt")
VALUES (1, TIMESTAMPTZ '2025-11-21T00:00:00Z', 'Unit Level Testing', 'Unit', TIMESTAMPTZ '2025-11-21T00:00:00Z');
INSERT INTO "TestLevels" ("Id", "CreatedAt", "Description", "Name", "UpdatedAt")
VALUES (2, TIMESTAMPTZ '2025-11-21T00:00:00Z', 'Integration Level Testing', 'Integration', TIMESTAMPTZ '2025-11-21T00:00:00Z');
INSERT INTO "TestLevels" ("Id", "CreatedAt", "Description", "Name", "UpdatedAt")
VALUES (3, TIMESTAMPTZ '2025-11-21T00:00:00Z', 'System Level Testing', 'System', TIMESTAMPTZ '2025-11-21T00:00:00Z');
INSERT INTO "TestLevels" ("Id", "CreatedAt", "Description", "Name", "UpdatedAt")
VALUES (4, TIMESTAMPTZ '2025-11-21T00:00:00Z', 'Acceptance Level Testing', 'Acceptance', TIMESTAMPTZ '2025-11-21T00:00:00Z');

CREATE INDEX "IX_TestCases_TestLevelId" ON "TestCases" ("TestLevelId");

CREATE INDEX "IX_TestResults_TestCaseId" ON "TestResults" ("TestCaseId");

CREATE INDEX "IX_TestResults_TestRunId" ON "TestResults" ("TestRunId");

SELECT setval(
    pg_get_serial_sequence('"TestLevels"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "TestLevels") + 1,
        nextval(pg_get_serial_sequence('"TestLevels"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251229214018_InitialCreate', '9.0.11');

COMMIT;

-- Create the 'request_db' database if it does not exist
CREATE DATABASE request_db OWNER test_user;
GRANT ALL PRIVILEGES ON DATABASE request_db TO test_user;

-- Create tables for "request_db".
\c request_db;

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "ResultMasters" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ResultMasters" PRIMARY KEY ("Id")
);

CREATE TABLE "StatusMasters" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_StatusMasters" PRIMARY KEY ("Id")
);

CREATE TABLE "Requests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DirectoryPath" text NOT NULL,
    "TestLevelId" integer NOT NULL,
    "StatusId" integer NOT NULL,
    "ResultId" integer NOT NULL,
    "RegisteredAt" timestamp with time zone NOT NULL,
    "UpdateAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Requests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Requests_ResultMasters_ResultId" FOREIGN KEY ("ResultId") REFERENCES "ResultMasters" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Requests_StatusMasters_StatusId" FOREIGN KEY ("StatusId") REFERENCES "StatusMasters" ("Id") ON DELETE RESTRICT
);

INSERT INTO "ResultMasters" ("Id", "CreatedAt", "Name", "UpdatedAt")
VALUES (1, TIMESTAMPTZ '2025-11-21T00:00:00Z', 'Unknown', TIMESTAMPTZ '2025-11-21T00:00:00Z');
INSERT INTO "ResultMasters" ("Id", "CreatedAt", "Name", "UpdatedAt")
VALUES (2, TIMESTAMPTZ '2025-11-21T00:00:00Z', 'Passed', TIMESTAMPTZ '2025-11-21T00:00:00Z');
INSERT INTO "ResultMasters" ("Id", "CreatedAt", "Name", "UpdatedAt")
VALUES (3, TIMESTAMPTZ '2025-11-21T00:00:00Z', 'Failed', TIMESTAMPTZ '2025-11-21T00:00:00Z');

INSERT INTO "StatusMasters" ("Id", "CreatedAt", "Name", "UpdatedAt")
VALUES (1, TIMESTAMPTZ '2025-11-21T00:00:00Z', 'Not started', TIMESTAMPTZ '2025-11-21T00:00:00Z');
INSERT INTO "StatusMasters" ("Id", "CreatedAt", "Name", "UpdatedAt")
VALUES (2, TIMESTAMPTZ '2025-11-21T00:00:00Z', 'Running', TIMESTAMPTZ '2025-11-21T00:00:00Z');
INSERT INTO "StatusMasters" ("Id", "CreatedAt", "Name", "UpdatedAt")
VALUES (3, TIMESTAMPTZ '2025-11-21T00:00:00Z', 'Completed(success)', TIMESTAMPTZ '2025-11-21T00:00:00Z');
INSERT INTO "StatusMasters" ("Id", "CreatedAt", "Name", "UpdatedAt")
VALUES (4, TIMESTAMPTZ '2025-11-21T00:00:00Z', 'Completed(failed)', TIMESTAMPTZ '2025-11-21T00:00:00Z');

CREATE INDEX "IX_Requests_ResultId" ON "Requests" ("ResultId");

CREATE INDEX "IX_Requests_StatusId" ON "Requests" ("StatusId");

SELECT setval(
    pg_get_serial_sequence('"ResultMasters"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "ResultMasters") + 1,
        nextval(pg_get_serial_sequence('"ResultMasters"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"StatusMasters"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "StatusMasters") + 1,
        nextval(pg_get_serial_sequence('"StatusMasters"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251231215744_InitialCreate', '9.0.11');

COMMIT;
