-- Create tables for "test_db"
GRANT ALL PRIVILEGES ON DATABASE test_db TO test_user;

\c test_db;

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Environments" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Environments" PRIMARY KEY ("Id")
);

CREATE TABLE "TestCases" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(200) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TestCases" PRIMARY KEY ("Id")
);

CREATE TABLE "TestLevels" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(50) NOT NULL,
    "DisplayName" character varying(100) NOT NULL,
    "Description" character varying(2000) NOT NULL,
    "SortOrder" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "Name" character varying(100) NOT NULL,
    CONSTRAINT "PK_TestLevels" PRIMARY KEY ("Id")
);

CREATE TABLE "TestStatuses" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(100) NOT NULL,
    "DisplayName" character varying(100) NOT NULL,
    "IsSuccess" boolean NOT NULL,
    "IsFailed" boolean NOT NULL,
    "IsSkipped" boolean NOT NULL,
    "IsExcluded" boolean NOT NULL,
    "IsInProgress" boolean NOT NULL,
    "IsTerminal" boolean NOT NULL,
    "SortOrder" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TestStatuses" PRIMARY KEY ("Id")
);

CREATE TABLE "EnvironmentVersions" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Os" character varying(200) NOT NULL,
    "RunTime" character varying(2000) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "EnvironmentId" bigint NOT NULL,
    "VersionNumber" bigint NOT NULL,
    "IsLatest" boolean NOT NULL,
    CONSTRAINT "PK_EnvironmentVersions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EnvironmentVersions_Environments_EnvironmentId" FOREIGN KEY ("EnvironmentId") REFERENCES "Environments" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TestExecutions" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Revision" text NOT NULL,
    "EnvironmentId" bigint NOT NULL,
    "ExecutedAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TestExecutions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TestExecutions_Environments_EnvironmentId" FOREIGN KEY ("EnvironmentId") REFERENCES "Environments" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TestCaseVersions" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(255) NOT NULL,
    "Description" character varying(2000) NOT NULL,
    "VersionNumber" bigint NOT NULL,
    "TestLevelId" bigint NOT NULL,
    "TestCaseId" bigint NOT NULL,
    "IsLatest" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TestCaseVersions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TestCaseVersions_TestCases_TestCaseId" FOREIGN KEY ("TestCaseId") REFERENCES "TestCases" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TestCaseVersions_TestLevels_TestLevelId" FOREIGN KEY ("TestLevelId") REFERENCES "TestLevels" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "TestExecutionItems" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TestExecutionId" bigint NOT NULL,
    "ExecutedAt" timestamp with time zone NOT NULL,
    "EnvironmentId" bigint NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TestExecutionItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TestExecutionItems_EnvironmentVersions_EnvironmentId" FOREIGN KEY ("EnvironmentId") REFERENCES "EnvironmentVersions" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TestExecutionItems_TestExecutions_TestExecutionId" FOREIGN KEY ("TestExecutionId") REFERENCES "TestExecutions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TestResults" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ActualResult" text NOT NULL,
    "TestExecutionItemId" bigint NOT NULL,
    "TestCaseVersionId" bigint NOT NULL,
    "Message" text,
    "StatusId" bigint NOT NULL,
    "ExecutedAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TestResults" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TestResults_TestCaseVersions_TestCaseVersionId" FOREIGN KEY ("TestCaseVersionId") REFERENCES "TestCaseVersions" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TestResults_TestExecutionItems_TestExecutionItemId" FOREIGN KEY ("TestExecutionItemId") REFERENCES "TestExecutionItems" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TestResults_TestStatuses_StatusId" FOREIGN KEY ("StatusId") REFERENCES "TestStatuses" ("Id") ON DELETE RESTRICT
);

INSERT INTO "TestLevels" ("Id", "Code", "CreatedAt", "Description", "DisplayName", "Name", "SortOrder", "UpdatedAt")
VALUES (1, 'UNIT', TIMESTAMPTZ '2025-11-21T00:00:00Z', 'Tests that validate the functionality of a specific section of code, usually at the function level.', 'Unit Test', 'Unit', 1, TIMESTAMPTZ '2025-11-21T00:00:00Z');
INSERT INTO "TestLevels" ("Id", "Code", "CreatedAt", "Description", "DisplayName", "Name", "SortOrder", "UpdatedAt")
VALUES (2, 'INTEGRATION', TIMESTAMPTZ '2025-11-21T00:00:00Z', 'Tests that validate the interaction between different components or systems.', 'Integration Test', 'Integration', 2, TIMESTAMPTZ '2025-11-21T00:00:00Z');
INSERT INTO "TestLevels" ("Id", "Code", "CreatedAt", "Description", "DisplayName", "Name", "SortOrder", "UpdatedAt")
VALUES (3, 'SYSTEM', TIMESTAMPTZ '2025-11-21T00:00:00Z', 'Tests that validate the complete and integrated system.', 'System Test', 'System', 3, TIMESTAMPTZ '2025-11-21T00:00:00Z');
INSERT INTO "TestLevels" ("Id", "Code", "CreatedAt", "Description", "DisplayName", "Name", "SortOrder", "UpdatedAt")
VALUES (4, 'ACCEPTANCE', TIMESTAMPTZ '2025-11-21T00:00:00Z', 'Tests that validate the system against the business requirements and user needs.', 'Acceptance Test', 'Acceptance', 4, TIMESTAMPTZ '2025-11-21T00:00:00Z');

INSERT INTO "TestStatuses" ("Id", "Code", "CreatedAt", "DisplayName", "IsExcluded", "IsFailed", "IsInProgress", "IsSkipped", "IsSuccess", "IsTerminal", "SortOrder", "UpdatedAt")
VALUES (1, 'PASSED', TIMESTAMPTZ '2025-11-21T00:00:00Z', 'Passed', FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, 1, TIMESTAMPTZ '2025-11-21T00:00:00Z');
INSERT INTO "TestStatuses" ("Id", "Code", "CreatedAt", "DisplayName", "IsExcluded", "IsFailed", "IsInProgress", "IsSkipped", "IsSuccess", "IsTerminal", "SortOrder", "UpdatedAt")
VALUES (2, 'FAILED', TIMESTAMPTZ '2025-11-21T00:00:00Z', 'Failed', FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, 2, TIMESTAMPTZ '2025-11-21T00:00:00Z');
INSERT INTO "TestStatuses" ("Id", "Code", "CreatedAt", "DisplayName", "IsExcluded", "IsFailed", "IsInProgress", "IsSkipped", "IsSuccess", "IsTerminal", "SortOrder", "UpdatedAt")
VALUES (3, 'SKIPPED', TIMESTAMPTZ '2025-11-21T00:00:00Z', 'Skipped', FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, 3, TIMESTAMPTZ '2025-11-21T00:00:00Z');
INSERT INTO "TestStatuses" ("Id", "Code", "CreatedAt", "DisplayName", "IsExcluded", "IsFailed", "IsInProgress", "IsSkipped", "IsSuccess", "IsTerminal", "SortOrder", "UpdatedAt")
VALUES (4, 'IN_PROGRESS', TIMESTAMPTZ '2025-11-21T00:00:00Z', 'In Progress', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 4, TIMESTAMPTZ '2025-11-21T00:00:00Z');
INSERT INTO "TestStatuses" ("Id", "Code", "CreatedAt", "DisplayName", "IsExcluded", "IsFailed", "IsInProgress", "IsSkipped", "IsSuccess", "IsTerminal", "SortOrder", "UpdatedAt")
VALUES (5, 'NOT EXECUTED', TIMESTAMPTZ '2025-11-21T00:00:00Z', 'Not executed', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 5, TIMESTAMPTZ '2025-11-21T00:00:00Z');
INSERT INTO "TestStatuses" ("Id", "Code", "CreatedAt", "DisplayName", "IsExcluded", "IsFailed", "IsInProgress", "IsSkipped", "IsSuccess", "IsTerminal", "SortOrder", "UpdatedAt")
VALUES (6, 'EXCLUDED', TIMESTAMPTZ '2025-11-21T00:00:00Z', 'Excluded', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 6, TIMESTAMPTZ '2025-11-21T00:00:00Z');

CREATE UNIQUE INDEX "IX_Environments_Name" ON "Environments" ("Name");

CREATE INDEX "IX_EnvironmentVersions_EnvironmentId" ON "EnvironmentVersions" ("EnvironmentId");

CREATE UNIQUE INDEX "IX_EnvironmentVersions_Os_RunTime_EnvironmentId_VersionNumber" ON "EnvironmentVersions" ("Os", "RunTime", "EnvironmentId", "VersionNumber");

CREATE UNIQUE INDEX "IX_TestCases_Code" ON "TestCases" ("Code");

CREATE UNIQUE INDEX "IX_TestCaseVersions_Name_Description_TestLevelId_TestCaseId_Ve~" ON "TestCaseVersions" ("Name", "Description", "TestLevelId", "TestCaseId", "VersionNumber");

CREATE INDEX "IX_TestCaseVersions_TestCaseId" ON "TestCaseVersions" ("TestCaseId");

CREATE INDEX "IX_TestCaseVersions_TestLevelId" ON "TestCaseVersions" ("TestLevelId");

CREATE INDEX "IX_TestExecutionItems_EnvironmentId" ON "TestExecutionItems" ("EnvironmentId");

CREATE INDEX "IX_TestExecutionItems_TestExecutionId" ON "TestExecutionItems" ("TestExecutionId");

CREATE INDEX "IX_TestExecutions_EnvironmentId" ON "TestExecutions" ("EnvironmentId");

CREATE UNIQUE INDEX "IX_TestExecutions_Revision_EnvironmentId" ON "TestExecutions" ("Revision", "EnvironmentId");

CREATE INDEX "IX_TestResults_StatusId" ON "TestResults" ("StatusId");

CREATE INDEX "IX_TestResults_TestCaseVersionId" ON "TestResults" ("TestCaseVersionId");

CREATE UNIQUE INDEX "IX_TestResults_TestExecutionItemId_TestCaseVersionId_ExecutedAt" ON "TestResults" ("TestExecutionItemId", "TestCaseVersionId", "ExecutedAt");

SELECT setval(
    pg_get_serial_sequence('"TestLevels"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "TestLevels") + 1,
        nextval(pg_get_serial_sequence('"TestLevels"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"TestStatuses"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "TestStatuses") + 1,
        nextval(pg_get_serial_sequence('"TestStatuses"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260717214430_InitialCreate', '9.0.11');

COMMIT;

