# Build application 
FROM mcr.microsoft.com/dotnet/sdk:8.0 as build_application

# COPY source code of application.
COPY ./TestManagement.APP /Source/

# Change working directory to the sample project folder.
WORKDIR /Source/TestManagement.APP

# build the application.
RUN dotnet restore && \
    dotnet publish -c debug -o /App --no-restore

# Start building running environment.
# It can not build application, only run it to avoid change the application or api.
FROM mcr.microsoft.com/dotnet/aspnet:8.0

RUN apt-get update

# Copy application from "build" containers.
WORKDIR /App/application
COPY --from=build_application /App ./
COPY ./TestManagement.APP/TestManagement.APP/pass.txt /etc/pass.txt

# Start 
ENTRYPOINT ["dotnet", "TestManagement.APP.dll"]
